name: Continuous Integration
on:
  pull_request:
    branches:
      - main
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Instalar e rodar o Pylint
        run: |
          pip install pylint
          pylint main.py